#!/bin/bash
set -euo pipefail
cargo build --release --example simple-evolve

arg=${1:-}

if [ "$arg" == "debug" ]; then
    export RUST_LOG=debug
    target/release/examples/simple-evolve 2>&1 | less -S
else
    export RUST_LOG=info
    target/release/examples/simple-evolve | tee run.txt
fi
