#!/bin/bash
set -euo pipefail
program=evolve
cargo build --release --example $program

arg=${1:-}

if [ "$arg" == "debug" ]; then
    export RUST_LOG=debug
    target/release/examples/$program 2>&1 | less -S
else
    export RUST_LOG=info
    target/release/examples/$program | tee run.txt
fi
